### ISSUE TITLE
[Steam feedback] Look at loot drop rates of Zeds

### ISSUE THREAD

**Issue by HugoQwerty** [robotex140/Hydrocraft#18]
Feedback from Steam:

"You might want to check the drop rate, and the reason for the existence of people having manometers in their pockets in the 90's USA :)

Same goes for unkown seeds packets and shotgun silencers. Zeds were placeholders for items that were too rare to be found elsewhere. except that when loot was updated in core game, the workaround was never adressed in hydrocraft, so we have Zeds dropping really weird stuff"

Re silencers, maybe we could make them craftable instead, locked behind high metal working and aiming - a reward for gun users, and perhaps a tradeable commodity in MP.

**Comment by HugoQwerty** [comment]
Seeds, maybe we could add those to sheds, garages, and those houses that have lots of seeds.  Manometer would presumably be warehouse crates.

**Comment by robotex140** [comment]
Seedspackets I think we should keep in the zed loot. Although very unrealistic, we have so many plants, and now with the sprites provided by Zombifarm, I think we will be adding more soon so existing plants like watermelons and pumpkins can be grown. Because of this, I think the seed packets need a infinite source, to ensure you can plant them all. Other items I agree, if we can find a better place for those items, we should move them

**Comment by robotex140** [comment]
actually for manometer, maybe we can make it into a item crafted from metal and glass. Technically, all a manometer is, is a bent tube with one opening to atmosphere, and the other into the vessel being measured

**Comment by robotex140** [comment]
can we close this?

**Comment by HugoQwerty** [comment]
Yes.
